In [1]:
import numpy as np

In [2]:
array1=np.arange(start=1,stop=10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [3]:
value=array1[2]
print(value)

3


In [4]:
print(array1[-1],array1[-2])

9 8


In [5]:
array2d=array1.reshape(-1,3)

In [6]:
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(array2d[0,1])

2


In [8]:
print(array2d[0:2,0:2])

[[1 2]
 [4 5]]


In [9]:
print(array2d[0:2,0])

[1 4]


In [10]:
print(array2d[0])

[1 2 3]


In [11]:
print(array2d[1])

[4 5 6]


In [12]:
print(array2d[0].shape)

(3,)
