In [1]:
import numpy as np

In [2]:
array1=np.arange(start=1,stop=10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [3]:
value=array1[2]
print(value)

3


In [4]:
print(array1[-1],array1[-2])

9 8


In [5]:
array2d=array1.reshape(-1,3)

In [6]:
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(array2d[0,1])

2


In [8]:
print(array2d[0:2,0:2])

[[1 2]
 [4 5]]


In [9]:
print(array2d[0:2,0])

[1 4]


In [10]:
print(array2d[0])

[1 2 3]


In [11]:
print(array2d[1])

[4 5 6]


In [12]:
print(array2d[0].shape)

(3,)


In [13]:
array3=array1[array1>5]

In [14]:
print(array3)

[6 7 8 9]


In [18]:
# np.sort(ndarray): 인자로 들어온 원행렬은 그대로 유지, 행렬의 정렬된 행렬 반환
# ndarray.sort(): 원행렬 자체를 정렬한 형태로 변환, 반환 값 None
# default는 오름차, 내림차는 [::-1]
# 2차원 배열에서는 앞에서 다룬 axis를 기준으로 sort함
# axis = 0 은 row
# axis = 1 은 col

In [19]:
# argsort(): 원본 행렬 정렬시 정렬된 행렬의 원래 인덱스가 필요할때
# np.argsort()를 이용
# 인덱스 값이 아니라 index 자체가 필요할 경우 사용!!!!!

In [17]:
arg_array=np.array([3,1,9,5])
sort_array1=np.sort(arg_array)
print(arg_array)
print(sort_array1)
arg_array.sort()
print(arg_array)

[3 1 9 5]
[1 3 5 9]
[1 3 5 9]


In [20]:
sort_array1_desc=np.sort(arg_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [22]:
array2d=np.array([[8,12],
                 [7,1]])
sort_array2d_axis0=np.sort(array2d, axis=0)
print(sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]
