In [1]:
import numpy as np
import xgboost
import lightgbm

In [2]:
#ndarray: n차원 배열
#차원이 높아진 다는 것은 그 직전 차원이 연속되게 많아지는것
#ndarray에서는 같은 type 만 넣기가 가능! 형 변환을 해서 처리해주는 경우가 있을것!

In [8]:
array1=np.array([1,2,3])
print(array1)
#shape? 열의 shape , 를 포함!
print(array1.shape)

[1 2 3]
(3,)


In [7]:
array2=np.array([[1,2,3],
               [2,3,4]])
print(array2)
#2 x 3 shape
print(array2.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)
