In [1]:
import numpy as np

In [2]:
#2차원인 경우 행이 axis 0,열이 axis 1 !

In [4]:
array1=np.arange(10)

In [5]:
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
array2=np.zeros((3,2),dtype='int32')
print(array2)

[[0 0]
 [0 0]
 [0 0]]


In [8]:
array3=np.ones((3,2))
print(array3)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
zero_array=np.zeros((3,2),dtype='int32')
one_array=np.ones((3,2))

In [10]:
array2=array1.reshape(2,5)

print(array2)
array3=array1.reshape(5,2)
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print(array3d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [12]:
array5=array3d.reshape(-1,1)

In [14]:
print(array5)
print(array5.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [17]:
array1d=array3d.reshape(-1,)

In [18]:
print(array1d)

[0 1 2 3 4 5 6 7]
